### ISSUE TITLE
Primer3 interface

### ISSUE THREAD

**Issue by EdGreen21** [argschwind/TAPseq#1]
Great code Andreas, and as far as I can tell the only R code interfacing with the new Primer3 v.2.5.0. Thought about splitting out the primer design and validation parts of the code from the TSIO object dependency and submitting that separately to CRAN?

**Comment by argschwind** [comment]
Hi Ed,

Thanks for your comment. My initial idea was to write a general Primer3 package and build TAPseq on top of that. But since Primer3 can tackle many different tasks, its output is quite complicated and storing it in meaningful R-objects, like TsIO, would be challenging and time consuming. One could use low-level objects, such as lists, to store input and output of Primer3 regardless of the task, e.g.:

```r
input <- list(
  PRIMER_PRODUCT_SIZE_RANGE = 100-300
  PRIMER_SECONDARY_STRUCTURE_ALIGNMENT = 0
  PRIMER_NUM_RETURN = 5
  PRIMER_MAX_HAIRPIN_TH = 47.0
  PRIMER_INTERNAL_MAX_HAIRPIN_TH = 47.0
  PRIMER_MAX_END_STABILITY = 100.0
  PRIMER_MIN_LEFT_THREE_PRIME_DISTANCE = -1
  PRIMER_MIN_RIGHT_THREE_PRIME_DISTANCE = -1
  PRIMER_EXPLAIN_FLAG = 0
  PRIMER_LIBERAL_BASE = 0
  PRIMER_FIRST_BASE_INDEX = 0
  PRIMER_MAX_TEMPLATE_MISPRIMING = -1.00
  PRIMER_MAX_TEMPLATE_MISPRIMING_TH = -1.00
  PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING = -1.00
  PRIMER_PAIR_MAX_TEMPLATE_MISPRIMING_TH = -1.00
)
```

TAPseq utilizes such objects under the hood to interact with Primer3 (see: `createIORecord()` in tapseq_input.R and the functions in primer3_io.R) . They could certainly be put into a separate, smaller package if that was useful for the bioinformatics community.
